### ISSUE TITLE
mismatch between generate_hit_points() function

### ISSUE THREAD

**Issue by foolsbazar** [mtttech/thespian#5]
There is a mismatch between the way the function `generate_hit_points()` is defined in `attributes.py` and the way it is called in `thespian.py` at line 732. I feel you implemented multiclass handling in `attributes.py` but you still have to do it in `thespian.py`. 
I'm not  sure how you want to implement it, thus cannot provide a bugfix. In fact I'm actually opening the issue just for complimenting on the nice work you are doing, I'm really looking forward to see it working.

**Comment by mtttech** [comment]
Thank you. Ive seen a few issues since i started trying to implement multiclassing. Thats actually on the todo now. I have been stuck going back looking through it all
